myproject/myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),

]

myproject/users/urls.py
from django.conf.urls import url
from .views import (UserList, UserDetail, UserCreation, UserUpdate, UserDelete)
app_name = 'users'

urlpatterns = [
    url(r'^$', UserList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', UserDetail.as_view(), name='detail'),
    url(r'^nuevo$', UserCreation.as_view(), name='new'),
    url(r'^editar/(?P<pk>\d+)$', UserUpdate.as_view(), name='edit'),
    url(r'^borrar/(?P<pk>\d+)$', UserDelete.as_view(), name='delete'),
]

myproject/users/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    name = models.CharField(max_length=140)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    description = models.CharField(max_length=500)

myproject/users/views.py
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (CreateView, UpdateView, DeleteView)
from django.urls import reverse_lazy
from .models import User

class UserList(ListView):
    model = User

class UserDetail(DetailView):
    model = User


class UserCreation(CreateView):
    model = User
    success_url = reverse_lazy('users:new')
    fields = ['name', 'start_date', 'end_date', 'description']

class UserUpdate(UpdateView):
    model = User
    success_url = reverse_lazy('users:edit')
    fields = ['name', 'start_date', 'end_date', 'description']


class UserDelete(DeleteView):
    model = User
    success_url = reverse_lazy('users:delete')

myproject/users/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-
Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <title>{% block title %}Administración de usuarios{% endblock %}</title>
    <style>
        .form-create {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
        }
    </style>
</head>
<body class="text-center">
<div id="content" class="container">
    {% block content %} {% endblock %}
</div>
</body>
</html>

myproject/users/templates/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-
Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <title>{% block title %}Administración de usuarios{% endblock %}</title>
    <style>
        .form-create {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
        }
    </style>
</head>
<body class="text-center">
<div id="content" class="container">
    {% block content %} {% endblock %}
</div>
</body>
</html>

myproject/users/templates/user_confirm_delete.html
{% extends "user.html" %}
{% block content %}
    <form method="post">{% csrf_token %}
        <h3>
            ¿Estás seguro que deseas borrar el usuario "{{object.name}}"?
        </h3>
        <input type="submit" value="Eliminar" />
    </form>
{% endblock %}

myproject/users/templates/user_form.html
{% extends "user.html" %}
{% block content %}

    <h1>Crear Usuario</h1>
    <form class="form-create" method="post">
        <div class="">
            {% csrf_token %}
            {{ form.as_p }}
        </div>
        <input class="btn btn-lg btn-primary" type="submit" value="Guardar" />
    </form>
{% endblock %}

myproject/users/templates/user_list.html
{% extends "user.html" %}
{% block content %}
    <h1>Administración de cursos</h1>
    <p>
        <a class="btn btn-lg btn-primary"href="{% url "users:new" %}">Agregar
            curso</a>
    </p>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>id</th>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Opciones</th>
        </tr>
        </thead>
        <tbody>
        {% for user in object_list %}
            <tr>
                <td>{{ user.id}}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.description }}</td>
                <td>
                    <a href="{% url "users:detail" user.id %}">Ver</a> |
                    <a href="{% url "users:edit" user.id %}">Editar</a> |
                    <a href="{% url "users:delete" user.id %}">Borrar</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

myproject/users/templates/users/user_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <form method="post">{% csrf_token %}
        <h3>
            ¿Estás seguro que deseas borrar el usuario "{{object.name}}"?
        </h3>
        <input type="submit" value="Eliminar" />
    </form>
{% endblock %}

myproject/users/templates/users/user_detail.html
{% extends "base.html" %}
{% block content %}
    <h1>Detalles del Usuario: {{ user.name}} </h1>
    <table class="table">
        <thead>
        <tr>
            <th>id</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Fecha inicio</th>
            <th>Fecha finalización</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{user.id}}</td>
            <td>{{user.name}}</td>
            <td>{{user.description}}</td>
            <td>{{user.start_date |date:'Y-m-d'}}</td>
            <td>{{user.end_date |date:'Y-m-d'}}</td>
        </tr>
        </tbody>
    </table>
    <p>
        <a href="{% url "users:list" %}">Regresar</a>
    </p>
{% endblock %}

myproject/users/templates/users/user_form.html
{% extends "base.html" %}
{% block content %}

    <h1>Crear Usuario</h1>
    <form class="form-create" method="post">
        <div class="">
            {% csrf_token %}
            {{ form.as_p }}
        </div>
        <input class="btn btn-lg btn-primary" type="submit" value="Guardar" />
    </form>
{% endblock %}

myproject/users/templates/users/user_list.html
{% extends "base.html" %}
{% block content %}
    <h1>Administración de usuarios</h1>
    <p>
        <a class="btn btn-lg btn-primary"href="{% url "users:new" %}">Agregar
            usuario</a>
    </p>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>id</th>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Opciones</th>
        </tr>
        </thead>
        <tbody>
        {% for user in object_list %}
            <tr>
                <td>{{ user.id}}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.description }}</td>
                <td>
                    <a href="{% url "users:detail" user.id %}">Ver</a> |
                    <a href="{% url "users:edit" user.id %}">Editar</a> |
                    <a href="{% url "users:delete" user.id %}">Borrar</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}